highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://yangzhewen.github.io
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Zhewen Yang's website
name: Zhewen Yang （Lucas）
email: zyang122 AT jh DOT edu & zhewenyang AT outlook DOT com
email_full: zyang122@jh.edu
website: yangzhewen.github.io
website_full: https://yangzhewen.github.io
#github: yangzhewen
LinkedIn: zhewen-yang
#tel: +44 0000 0000000
#tel_full: tel:+440000000000
google_maps: 'https://goo.gl/maps/vZdkoff4N6oRxA9z7'
address:
#  street: 44 Perth Street
  postcode: 21218
  city: Baltimore
  country: USA
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
